In [ ]:
import numpy as np
import pandas as pd

import nltk
import string

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

import gensim
from gensim.utils import simple_preprocess

In [ ]:
from google.colab import files
upload = files.upload()

Saving IDTATextPreprocessing.csv to IDTATextPreprocessing (1).csv

In [ ]:
reviews = pd.read_csv("IDTATextPreprocessing.csv")

In [ ]:
reviews.head()

   Unnamed: 0                                             Review  Sentiment
0           0                     way plug u unless go converter          0
1           1                          good case excellent value          1
2           2                                      great jawbone          1
3           3  tie charger conversation last minutesmajor pro...          0
4           4                                          mic great          1

In [ ]:
del reviews["Unnamed: 0"]

In [ ]:
reviews.head()

                                              Review  Sentiment
0                     way plug u unless go converter          0
1                          good case excellent value          1
2                                      great jawbone          1
3  tie charger conversation last minutesmajor pro...          0
4                                          mic great          1

In [ ]:
#change the text column datatype to string
reviews = reviews.astype({'Review':'string'})

In [ ]:
#get the review text for preprocessing
text = reviews['Review']

In [ ]:
data = reviews.Review.values.tolist()

In [ ]:
data

['way plug u unless go converter',
 'good case excellent value',
 'great jawbone',
 'tie charger conversation last minutesmajor problem',
 'mic great',
 'jiggle plug get line right get decent volume',
 'several dozen several hundred contact imagine fun send one one',
 'razr owneryou must',
 'needle say waste money',
 'waste money time',
 'sound quality great',
 'impressed go original battery extend battery',
 'two seperated mere ft start notice excessive static garble sound headset',
 'good quality though',
 'design odd ear clip comfortable',
 'highly recommend one blue tooth phone',
 'advise everyone fool',
 'far good',
 'work great',
 'click place way make wonder long mechanism would last',
 'go motorolas website follow direction could get pair',
 'bought use kindle fire absolutely love',
 'commercial mislead',
 'yet run new battery two bar thats three day without charge',
 'bought mother problem battery',
 'great pocket pc phone combination',
 'ive own phone month say best mobile phone ive',
 'didnt think instruction provide helpful',
 'people couldnt hear talk pull earphone talk phone',
 'doesnt hold charge',
 'simple little phone use breakage unacceptible',
 'product ideal people like whose ear sensitive',
 'unusable move car freeway speed',
 'two year left contract hate phone',
 'car charger well ac charger include make sure never run juicehighy recommend',
 'need least min get phone book time first turn phonebattery life short',
 'kept well',
 'poor talk time performance',
 'case great work fine',
 'worthless product',
 'great camera thats mp pic nice clear great picture quality',
 'impressed product',
 'nice headset price right',
 'hear garbage audio',
 'excellent bluetooth headset',
 'feature want',
 'right mind gonna buy battery',
 'argue verizon regard drop call return phone two day',
 'case seem well make',
 'disappointed battery',
 'loud enough doesnt turn like',
 'good protection make phone bulky',
 'usable keyboard actually turn pda realworld useful machine instead neat gadget',
 'phone pretty sturdy ive never large problem',
 'love thing',
 'everything fine reasonable price ie',
 'disappointed',
 'even drop phone stream submerge second still work great',
 'happy complaint one regard sound quality end',
 'button bad',
 'essentially forget microsofts tech support',
 'really recommend faceplate since look nice elegant cool',
 'headphone great find think perhaps best purchase ive make last several year seriously',
 'buy different phone',
 'hold phone particular angle party hear clearly',
 'one big drawback mp player button phone front cover let pause skip song lock second',
 'week later activate suddenly die',
 'feel comfortable headset wear glass get way sometimes',
 'great ipod',
 'device great several situation',
 'mic doesnt work',
 'even bmw series fairly quiet trouble hearing person say',
 'great choice',
 'nice dock station home work',
 'beautiful phone',
 'love product',
 'buy dwrongly advertised',
 'great little item',
 'love phone handy lot feature',
 'purchase within day longer work',
 'wear everyday hold well',
 'good bargain',
 'well package arrive time work intend',
 'battery run quickly',
 'item work great broke month use',
 'headset easy use everyone love',
 'phone work great',
 'construction headset poor',
 'product excellent work well verizon one boy cheaper',
 'phone load super',
 'product cost much one expect work far well great ease thing',
 'make sturdy',
 'work great',
 'ear bud play music one ear',
 'dont waste money',
 'order',
 'plan use car forget',
 'found product waaay big',
 'best ive found far ive try bluetooths one best quality listener well ease use',
 'im disappointed decision',
 'integrate seamlessly motorola razr phone',
 'buyer beware could flush money right toilet',
 'definitely bargain',
 'price good free shipping good purchase',
 'receive supposedly new motorola apparently match phone charger',
 'prosgood camera nice picture also cool style like black white',
 'thats huge design flaw unless im use correctly dont think case',
 'love headset jabra bluetooth headset great reception good ear piece comfortable fit',
 'camera although rat impressive megapixels render image fall well expectation relatively high resolution',
 'purcashed car charger work',
 'sound quality end excellent use headset call wife ask wife use headset call',
 'phone slim light display beautiful',
 'little geeky think thats sex toast rock ooze sex right battery embed sleek stylish leather case',
 'great product fast shipping',
 'absolutely great',
 'keyboard nice compromise full qwerty basic cell phone number keypad',
 'get phone around end may im completely unhappy',
 'comfortable ear',
 'winner u',
 'setup couldnt simpler',
 'ive try several different earpiece cell phone jabra one first one ive found fit ear comfortably',
 'could get strong enough signal',
 'iam pleased purchase',
 'bad quality',
 'get job do',
 'great audio',
 'basically service bad',
 'work cell phone plug set charger',
 'ive bluetooth week really like',
 'bt headset disapoinment',
 'small dont even realize get use',
 'accompany software almost brilliant',
 'headset work great package nicely avoid damage',
 'definitly recommend',
 'buyerbe careful',
 'majority logitech earbud headset fail',
 'good stuff price',
 'headset work peachykeen',
 'house get drop coverage upstairs coverage basement',
 'voice recognition tremendous',
 'waste',
 'several different minute call experienced drop area bar',
 'happy item',
 'disappointed',
 'phone take forever charge like hour literally',
 'get phone reccomendation relative im glad',
 'waste time',
 'reception poor',
 'item state include description include',
 'month screen go black sudden',
 'hop',
 'audio quality poor poor',
 'absolutely problem headset link blackberry curve',
 'know sound funny seem like sketchy technology wouldnt work wellwell one work great',
 'ive bought wire headphone sound well',
 'phone fast send kind message web browsing significantly faster previous phone use',
 'nice quality build unlike cheap',
 'item fantastic work perfectly',
 'love color',
 'wi superb',
 'whine internet goesthe use thing less like',
 'great charger',
 'essentially communication tool communicate',
 'work like charm work one get phone',
 'still maintain monkey shouldnt make headphone obviously dont share enough dna copy design human',
 'great value',
 'doesnt work bougth lc work',
 'look sharp screen nice clear great graphic',
 'doesnt last long',
 'one thing hate mode set button side',
 'excellent service',
 'thank waste money',
 'bethe audio quality poor',
 'igo charger tip really great',
 'file browser offer option one needshandsfree great',
 'superb phone great network',
 'connect wife bluetoothmotorola h phone work like charm whether phone pocket case',
 'put late o vg like slow crawl lock every',
 'recognizes phone storage device',
 'like loud buzzing override conversation phone',
 'dont buy product',
 'ive bluetoooth headset time still comfortable way fit ear',
 'sound quality good functionality awesome',
 'phone thorn side really abhor',
 'recently problem could stay connect minute disconnect',
 'incredible',
 'design flaw',
 'great phone',
 'waste buck',
 'check voice mail night keypad backlight turn second first message im lose',
 'replacement die week',
 'ring toneoverall good phone buy',
 'lately extremely nice helpful phone',
 'problem wit hit drop signal',
 'impressed',
 'light weight hardly notice',
 'youll love thin',
 'bad choice',
 'pleather case doesnt fit',
 'useless phone simply deaf',
 'color even prettier thought would graphic incredibly sharp',
 'think good investment',
 'make strange tick noise end call',
 'best electronics available fm transmitter',
 'battery last hour',
 'great headset impressed h',
 'mega pixel camera part phone reasonably good',
 'ive nearly year work great',
 'good transmit audio',
 'send back',
 'bother contact company dollar product learn lesson bought form online anyway',
 'hate earbugs avoid phone mean',
 'great price also',
 'range decent ive able roam around house phone living room receptionsound quality issue',
 'fast service',
 'would highly recommend',
 'would recommend',
 'also didnt like button felt like would crack use',
 'bad phone ever',
 'im still infatuate phone',
 'freeze frequently',
 'kind embarrass use look mostly embarrass childlike company',
 'simple lightweight great fit',
 'id expect well consumer experience motorola',
 'there horrible tick sound background call never experienced',
 'certainly comfortable functionality decent',
 'usually dont like headband one lightweight doesnt mess hair',
 'im bit disappointed',
 'phone year tell great',
 'order sony ericsson wi think work thats first use',
 'battery completely useless',
 'big waste time',
 'dont waste one',
 'great sound service',
 'really pleased product far',
 'one favorite purchase ever',
 'best bluetooth market',
 'authentic leather nice shine comfort recommend case',
 'excite get headset thought really cute',
 'make mistake',
 'big disappointment calendar sync',
 'phone unusable new',
 'bad customer service ever',
 'additional ear gel provide instruction whatsoever',
 'defeat purpose bluetooth headset',
 'worth every penny',
 'excellent wallet type phone case',
 'nice headphone price work great',
 'internet excrutiatingly slow',
 'comfortable wear well probably important aspect use case',
 'fit like glove strong secure durable',
 'gosh best phone ever',
 'attractive appear good quality',
 'love feature form factor',
 'product strong rubberpetroleum smell unbearable cause return',
 'poor quality service',
 'cable look thin flimsy scary',
 'great earpiece',
 'excellent hand free tool',
 'great use home stereo',
 'good product incredible value',
 'month work flawlessly far',
 'work great',
 'absolutel junk',
 'one didnt work either',
 'battery life real good',
 'return hour later',
 'great item',
 'dont waste money',
 'love headset',
 'drain player may also potentially fry',
 'work perfectly',
 'unreliable im give',
 'give star sound quality',
 'avoid one',
 'reversible plug work great',
 'waste little money earpiece',
 'good phone',
 'best rotate feature helpful',
 'comfort whole family',
 'good product good seller',
 'love bluetooth',
 'first doesnt wear well',
 'impressed headset plantronics',
 'get small adorable',
 'great phone',
 'wouldnt recommend buying product',
 'piece junk',
 'poorly contstruct hinge',
 'item great instal let charge overnite work good every since problem',
 'great phone',
 'dont buy',
 'excellent phone',
 'purchase phone',
 'voice recognition thru handset excellent',
 'hand best phone ive ever',
 'work great cat attack phone scratch protective strip instead destroy screen',
 'one work price right',
 'customer service terrible',
 'battery life still long enough motorola razor vi',
 'send back',
 'know make wise decision',
 'someone shouldve invent sooner',
 'good price',
 'everything work first trythe device certainly engineer clever way construction feel good',
 'receive quickly work great',
 'work great',
 'many people complain found headset microphone weak',
 'year old nokia tracfone hold charge lot well',
 'care consumer one bit',
 'good battery get really fast',
 'instruction manual lack',
 'also slim enough fit alarm clock dock station without remove case',
 'phone hold charge like new',
 'battery unreliable well service use antena',
 'uncomfortable sound quality quite poor compare phone razr previous wire headset plug lg',
 'gotten lot compliment',
 'definitely must state allow cell phone usage drive',
 'want money back',
 'love device',
 'also happy price',
 'order product first unhappy immediately',
 'ngage still lack earbuds',
 'able voice dial car problem',
 'bar cell phone home cant hear anything',
 'good item low price',
 'howeverthe riingtones best neither game',
 'plug work well',
 'amazon suck',
 'rip charge shipping',
 'comfortable',
 'battery work well replacement original come phone year ago',
 'reception excellent',
 'fit comfortably either ear sound clear loud charge last couple day',
 'clear quality sound dont mess sound ipod since sound button headset',
 'long last battery dont recharge frequentyly flip phone',
 'obviously problem adhesive',
 'disappoint',
 'inexpensive piece would still expect well quality',
 'practically useless add kind boost reception bought',
 'excellent sound quality',
 'happy',
 'piece junk broke phone day',
 'new battery work great phone',
 'bad customer service',
 'ive drop phone time say even concrete phone still great knock wood',
 'reception terrible full static',
 'good audio quality',
 'little device transform organizational capability make life whole lot easy',
 'sit vehicle cradle belt headset lose signal',
 'jerk phone',
 'work like charm work advertised',
 'comfortable nice range good battery life',
 'network coverage los angeles horrible',
 'excellent starter wireless headset',
 'loudspeaker option great bumper light appeal',
 'thing think could improve sound leak headset',
 'first reception suck never bar ever',
 'phone get extremely hot',
 'microphone also work well accord people call applifies everything',
 'nice design quality',
 'also phone drop case go save specially drop face',
 'light easy use clear reception transmission',
 'bad fit way big',
 'definitely good',
 'awesome device',
 'waste money',
 'order motorola data cable get well finish work product',
 'love phone',
 'look headset long time ive get couldnt happier',
 'ill drivng along headset start ring reason',
 'display excellent camera good year',
 'battery life also great',
 'bad phone ive ever month',
 'good item work start problem auto reverse tape player',
 'embarassing also ear hurt try push ear plug ear',
 'protects phone side',
 'average phone bad battery life operates weak network',
 'clear skype call long battery life long range',
 'soyo technology suck',
 'great hand free device',
 'even take self portrait outside exterior display cool',
 'problem others mention',
 'try many many handsfree gadget one finally work well',
 'magical help',
 'bad piece crap ever along verizon customer service',
 'poor sound quality',
 'best phone market',
 'work well',
 'company ship product promptly work well',
 'exactly want',
 'picture resolution far comparablypriced phone offering today',
 'great deal',
 'excellent product satisfied purchase',
 'highly recommend encourage people give try',
 'well youd expect',
 'use earpiece left right thing stay ear',
 'great product price',
 'sound good reasonably price effective simple',
 'still wait im sure item would work well ever recieve',
 'disappointment',
 'prompt service',
 'excellent product price',
 'pleased headset',
 'dont waste money time',
 'especially love long battery life',
 'stupid keep buying new charger car charger cradle headphone car kit every time new phone come',
 'work great',
 'plantronics bluetooth excelent buy',
 'come verizon cingulair nicer cell phone first thing notice really bad service',
 'ill look new earpiece',
 'highly recommend device everyone',
 'jawbone era awesome',
 'receive white color battery go dead couple hoursthe original use last week still last longer thereplacement',
 'year battery go completely dead headset',
 'use several phone two year one best',
 'awesome new look fall',
 'first phone ive cheaply make',
 'att clear sound distort yell talk',
 'plastic break really easy clip',
 'price good',
 'dont make mistake',
 'oh forgot also mention weird color effect phone',
 'im use iriver spinn case fit fine',
 'also area unit broke im fond magnetic strap',
 'overall psyched phone appointment contact get great reception',
 'every thing phone work perfectly like',
 'another note phone appearance really look rather bland especially black model',
 'really easy',
 'sanyo survive dozen drop blacktop without ill effect',
 'fantastic earphone',
 'find cell phone right away enter car',
 'low quality',
 'highly recommend modest price cellular phone',
 'get well reception clarity phone ive',
 'warn stay away',
 'wish could return unit get back money',
 'awsome device work great',
 'use talk hour battery would literally drain die',
 'dont find bad unit come one earpad onlyi would recommend anyone',
 'displeased',
 'might gotten defect would risk buying built quality alone',
 'make case small difficult install',
 'restore phone like new performance',
 'would recommend purchasing jabra jx series work flawlessly moto q go figure',
 'search internet found one best value',
 'fit',
 'happy product',
 'screen size big key pad lit well enough camera quality excellent camera phone',
 'there really nothing bad say headset',
 'im glad found product amazon hard find wasnt high price',
 'portable work',
 'colleague get great receptiona little expensive performance great',
 'even fully charge go bed turn blue tooth wifi notice left morning',
 'ive also problem phone reading memory card always turn',
 'good wear hat sunglass',
 'timely shipment quality product',
 'nice solid keyboard',
 'well make fit surefire gx perfectly',
 'horrible phone',
 'bt battery junk',
 'would recommend others',
 'cant get software work computer',
 'disappointed',
 'poor voice clarity',
 'battery work great',
 'buyer remorse one',
 'disappointed accessoryone',
 'find inexcusable probably return phone perhaps change carrier',
 'look great strong',
 'tmobile service year pretty happy',
 'update procedure difficult cumbersome',
 'disappointment hate anything go ear',
 'great software motorolas',
 'delivery time',
 'easy use',
 'uncomfortable ear dont use lg vx env',
 'volume switch rocket unit destination unknown',
 'hold charge long time reasonably comfortable longwearing condition quality sound tremendous',
 'id like return',
 'keyboard really worthwhile usefulness sturdy enough dont expect problem',
 'verizons bill however difficult understand even though pricing plan simple',
 'charge overnight battery work great',
 'wont regret',
 'love phone',
 'disappointment',
 'user friendly',
 'unfortunately ability actually know receive call rather important feature phone pitiful respect',
 'exchange phone even problem',
 'result phone either stuck max volume mute',
 'pda rock',
 'super charge use small hybrid palmtopcameracellphone excels role',
 'would definitely recommend jabra btv look comfort clarity great price',
 'verizon year ago really like service',
 'pretty piece junk',
 'plug wrong size',
 'work described',
 'save money ive item month',
 'bad purchase',
 'well im satisfied',
 'bose noise cancel amaze important nyc commuter',
 'battery excellent bargain',
 'defective crap',
 'would give star able',
 'wear glass fit fine',
 'sound quality device unacceptableunless really quiet area almost hear nothing',
 'would recommend item anyone',
 'holster arrive match photo ad',
 'greatno problem',
 'earlier review note plug charger nothing happens',
 'frog phone charm adorable eye catch',
 'never know push hard enough right number time function want',
 'sound clear people talk amaze quality',
 'get aluminum case new palm vx work really wellit protect handheld perfectly far',
 'good product well make',
 'mobile phone tool must',
 'impressed job motorola sturdiness phone',
 'receive order well within shipping timeframe everything good work order overall excite source',
 'phone sturdy waterproof',
 'impressed would recommend item anyone',
 'complaint standard sound volume little low even turn',
 'thanks amazon thing need good price',
 'end slide edge pant back pocket instead',
 'go store bought new nokia phone work great',
 'work great',
 'really ugly',
 'horrible switch time',
 'noise shield incrediable',
 'real improvement',
 'razr battery good buy',
 'keep good work amazon',
 'refuse refund replace',
 'unfortunately easy accidentally activate gentletouch button accidentally touch phone face listen',
 'basically threw money window nothing',
 'great case price',

In [ ]:
def sent_to_words(sentences):
    for sentence in sentences:
        yield(gensim.utils.simple_preprocess(str(sentence)))

words = list(sent_to_words(data))

In [ ]:
print(words[:1][0][:30])

['way', 'plug', 'unless', 'go', 'converter']

In [ ]:
import gensim.corpora as corpora

# Create Dictionary
id2word = corpora.Dictionary(words)

# Create Corpus
texts = words

# Term Document Frequency
corpus = [id2word.doc2bow(text) for text in texts]

# View
print(corpus[:1][0][:30])

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)]

In [ ]:
from pprint import pprint

# number of topics
num_topics = 10

# Build LDA model
lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                       id2word=id2word,
                                       num_topics=num_topics)

# Print the Keyword in the 10 topics
pprint(lda_model.print_topics())
#doc_lda = lda_model[corpus]

WARNING:gensim.models.ldamulticore:too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy

[(0,
  '0.027*"work" + 0.023*"great" + 0.017*"phone" + 0.016*"sound" + 0.015*"well" '
  '+ 0.014*"one" + 0.012*"try" + 0.010*"ear" + 0.010*"headset" + 0.010*"good"'),
 (1,
  '0.029*"phone" + 0.012*"im" + 0.012*"fit" + 0.012*"ive" + 0.011*"headset" + '
  '0.009*"dont" + 0.009*"product" + 0.009*"ear" + 0.007*"one" + '
  '0.007*"around"'),
 (2,
  '0.026*"good" + 0.015*"case" + 0.015*"phone" + 0.015*"price" + '
  '0.015*"battery" + 0.014*"work" + 0.014*"would" + 0.008*"money" + '
  '0.008*"headset" + 0.008*"recommend"'),
 (3,
  '0.030*"use" + 0.022*"product" + 0.015*"phone" + 0.015*"really" + '
  '0.012*"work" + 0.012*"great" + 0.011*"easy" + 0.010*"charge" + '
  '0.010*"battery" + 0.010*"recommend"'),
 (4,
  '0.026*"phone" + 0.019*"work" + 0.018*"great" + 0.013*"dont" + 0.011*"would" '
  '+ 0.010*"quality" + 0.010*"money" + 0.008*"headset" + 0.008*"bluetooth" + '
  '0.008*"item"'),
 (5,
  '0.032*"great" + 0.028*"work" + 0.020*"use" + 0.019*"phone" + 0.015*"good" + '
  '0.015*"one" + 0.014*"price" + 0.012*"get" + 0.011*"sound" + '
  '0.010*"battery"'),
 (6,
  '0.047*"phone" + 0.032*"work" + 0.016*"well" + 0.016*"quality" + '
  '0.013*"poor" + 0.012*"use" + 0.009*"good" + 0.009*"time" + 0.008*"ear" + '
  '0.008*"get"'),
 (7,
  '0.045*"phone" + 0.024*"make" + 0.014*"great" + 0.014*"get" + 0.013*"call" + '
  '0.009*"dont" + 0.009*"ear" + 0.009*"sound" + 0.009*"horrible" + '
  '0.009*"comfortable"'),
 (8,
  '0.035*"phone" + 0.019*"great" + 0.019*"work" + 0.015*"love" + 0.013*"ive" + '
  '0.012*"good" + 0.011*"bad" + 0.010*"use" + 0.010*"well" + 0.009*"headset"'),
 (9,
  '0.021*"good" + 0.021*"get" + 0.012*"comfortable" + 0.012*"service" + '
  '0.012*"bad" + 0.012*"say" + 0.012*"ear" + 0.010*"great" + 0.010*"charge" + '
  '0.010*"quality"')]

In [ ]:
!pip install pyLDAvis==3.4.1

Requirement already satisfied: pyLDAvis==3.4.1 in /usr/local/lib/python3.10/dist-packages (3.4.1)
Requirement already satisfied: numpy>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (1.26.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (1.11.4)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (2.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (1.3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (3.1.2)
Requirement already satisfied: numexpr in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (2.8.8)
Requirement already satisfied: funcy in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (2.0)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (1.2.2)
Requirement already satisfied: gensim in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (4.3.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from pyLDAvis==3.4.1) (67.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.0->pyLDAvis==3.4.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.0->pyLDAvis==3.4.1) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.0->pyLDAvis==3.4.1) (2023.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.0->pyLDAvis==3.4.1) (3.2.0)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim->pyLDAvis==3.4.1) (6.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->pyLDAvis==3.4.1) (2.1.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->pyLDAvis==3.4.1) (1.16.0)

In [ ]:
#pip install pyldavis

In [ ]:
import pyLDAvis.gensim_models
import pyLDAvis

# Visualize the topics
pyLDAvis.enable_notebook()

LDAvis = pyLDAvis.gensim_models.prepare(lda_model, corpus, id2word)

LDAvis

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
5     -0.070753  0.000872       1        1  11.401318
6     -0.027279 -0.071764       2        1  11.314826
3     -0.071259  0.101443       3        1  11.026437
2     -0.033756  0.033186       4        1  10.665020
0     -0.047666 -0.033497       5        1  10.595397
8      0.003371 -0.000217       6        1  10.369831
7      0.063216 -0.091501       7        1   9.986971
4     -0.029417 -0.013708       8        1   8.667109
1      0.129514  0.086188       9        1   8.231319
9      0.084029 -0.011002      10        1   7.741772, topic_info=        Term        Freq       Total Category  logprob  loglift
71      work   89.000000   89.000000  Default  30.0000  30.0000
19       get   35.000000   35.000000  Default  29.0000  29.0000
64     phone  135.000000  135.000000  Default  28.0000  28.0000
90       use   55.000000   55.000000  Default  27.0000  27.0000
9      great   77.000000   77.000000  Default  26.0000  26.0000
..       ...         ...         ...      ...      ...      ...
49   headset    3.222231   43.697667  Topic10  -4.8397  -0.0487
130  product    3.222106   44.676119  Topic10  -4.8397  -0.0709
307       im    2.436214   19.427205  Topic10  -5.1193   0.4823
64     phone    2.436514  135.812020  Topic10  -5.1192  -1.4622
224     look    2.436390   20.285889  Topic10  -5.1192   0.4391

[732 rows x 6 columns], token_table=      Topic      Freq          Term
term
555       4  0.255580          able
555       6  0.511159          able
555       9  0.255580          able
1435     10  0.638772    accessable
964       2  0.846986  accidentally
...     ...       ...           ...
141       9  0.076275          year
101       2  0.632997           yet
101       6  0.316498           yet
1449      9  0.650199            za
994       1  0.630495          zero

[1363 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[6, 7, 4, 3, 1, 9, 8, 5, 2, 10])

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)